# Generated by Django 5.0.7 on 2024-07-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("spam_count", models.IntegerField(default=0)),
            ],
        ),
    ]
