# Generated by Django 5.0.7 on 2024-07-26 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0003_spam"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="phone_number",
            new_name="phone_no",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="phone_number",
            new_name="phone_no",
        ),
        migrations.RenameField(
            model_name="spam",
            old_name="phone_number",
            new_name="phone_no",
        ),
    ]
