# Generated by Django 5.0.7 on 2024-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0004_rename_phone_number_contact_phone_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spam",
            name="spam_count",
        ),
        migrations.AddField(
            model_name="spam",
            name="is_spam",
            field=models.BooleanField(default=True),
        ),
    ]
