# Generated by Django 5.0.7 on 2024-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Api", "0005_remove_spam_spam_count_spam_is_spam"),
    ]

    operations = [
        migrations.AddField(
            model_name="spam",
            name="spam_count",
            field=models.IntegerField(default=0),
        ),
    ]
